import type { Metadata } from "next";
import MainHeader from "./_components/MainHeader";
import "./globals.css";
import Navigation from "./_components/Navigation";
import localFont from 'next/font/local'

const segoeFont = localFont({ src: '../public/fonts/segoe.ttf' })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${segoeFont.className}`}
      >
        <div className="root grid grid-cols-[68px,1fr] divide-y divide-black/5">
          <MainHeader />
          <Navigation />
          <div>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
